server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    #phone photos of a tray is around 3 to 8 MB each and a request can accept many photos, so we made it to 400MB max.
    client_max_body_size 400M;

    location /api/reports/ {
        access_log off;
        proxy_pass http://backend:8000;
        proxy_set_header Host $http_host;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_read_timeout 300s;
    }

    location /api/ {
        proxy_pass http://backend:8000; #if any API request, forward it to the backend container
        proxy_set_header Host $http_host;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Real-IP $remote_addr;

        #segmentation and classification of 30 beans on a CPU takes a while. The 60s nginx default could cut the connection mid inference
        proxy_read_timeout 300s;
        proxy_send_timeout 300s;
    }

    # Missing module/assets must return 404 instead of the SPA HTML.
    location /assets/ {
        try_files $uri =404;
    }

    location /report/ {
        access_log off;
        add_header Referrer-Policy no-referrer always;
        try_files $uri $uri/ /index.html;
    }

    #requests that don't match /api/ are served directly by nginx 
    location / {
        try_files $uri $uri/ /index.html; #index.html as fallback if no file is matched
    }
}
